export class User {}

export const USER_ACTIONS = {
    SET_ALERT: "SET_ALERT",
    REMOVE_ALERT: "REMOVE_ALERT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    USER_LOADED: "USER_LOADED",
    AUTH_ERROR: "AUTH_ERROR",
    UPDATE_USER: "UPDATE_USER",
};
export type USER_ACTIONS = typeof USER_ACTIONS;
